---
# defaults file for roles/auto_nginx_config
jdk_package: java-1.8.0-openjdk.x86_64
tomcat_user: tomcat
tomcat_source: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz

tomcat_listen: 8080
tomcat_file: /usr/local/apache-tomcat-9.0.105

nginx_listen: 80
nginx_name: "nginx.example.com:{{ nginx_listen }}"
nginx_proxy_pass: http://localhost:8080

nginx_listen_ssl: 443
ssl_crt_path: /etc/pki/tls/certs/httpd.crt
ssl_key_path: /etc/pki/tls/private/httpd.key
ssl_country: "KR"
ssl_state: "AP Northeast"
ssl_city: "Seoul"
ssl_org: "Example Company"
ssl_ou: "Example Unit"
ssl_cn: "www3.example.com"
ssl_email: "root@localhost"
