---
# handlers file for roles/auto_nginx_config
- name: Restart Tomcat
  ansible.builtin.systemd:
    name: tomcat
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
