---
- name: Install Apache & Tomcat
  hosts: web_server
  tasks:
    - name: Role - auto_apache_config
      ansible.builtin.include_role:
        name: auto_apache_config
      vars:
        jdk_package: java-1.8.0-openjdk.x86_64
        tomcat_user: tomcat
        tomcat_source: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz
        tomcat_listen: 8080
        tomcat_file: /usr/local/apache-tomcat-9.0.105
        tomcat_secret: soldesk1.
        apache_listen: 80
        apache_name: "web.example.com:{{ apache_listen }}"
        apache_proxy_pass: http://localhost:8080/
        apache_listen_ssl: 443
        ssl_crt_path: /etc/pki/tls/certs/httpd.crt
        ssl_key_path: /etc/pki/tls/private/httpd.key
        ssl_country: "KR"
        ssl_state: "AP Northeast"
        ssl_city: "Seoul"
        ssl_org: "Example Company"
        ssl_ou: "Example Unit"
        ssl_cn: "web.example.com"
        ssl_email: "ansible@example.com"

- name: Web Test
  hosts: localhost
  tasks:
    - name: Install PIP3
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: PIP Install Package dnspython
      ansible.builtin.pip:
        name: dnspython
        state: present

    - name: Add DNS - web IN A 192.168.20.20 
      community.general.nsupdate:
        key_algorithm: hmac-sha256
        key_name: ddns-key
        key_secret: upcPpa6RKpen4/hFJ7p7TikAflVaisukxATItbES4Zw=
        server: 192.168.20.10
        zone: example.com
        record: web
        value: ["192.168.20.20"]

    - name: Request HTTPS
      ansible.builtin.uri:
        url: https://www.example.com:443
        status_code: 200
        validate_certs: false
      register: output
    
    - name: Result
      ansible.builtin.debug:
        var: output
