---
# defaults file for roles/ansible_log_config
jdk_package: java-1.8.0-openjdk

mongodb_baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/6.0/x86_64/
mongodb_package: mongodb-org

elastic_baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
elastic_rpm_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
elastic_package: elasticsearch-oss

rsyslog_listen: 1514
graylog_listen: 9000
