---
# tasks file for roles/ansible_log_config
- name: Enroll MongoDB Repostiroy
  ansible.builtin.yum_repository:
    name: mongodb-org-6.0
    description: MongoDB Repository
    baseurl: "{{ mongodb_baseurl }}"
    gpgcheck: no
    enabled: true

- name: Install Package
  ansible.builtin.dnf:
    name: 
      - "{{ mongodb_package }}"
      - "{{ jdk_package }}"
      - "{{ jdk_package }}-devel"
    state: present
  notify: Restart MongoDB
  changed_when: true

- name: Enroll Elasticsearch Repostiroy
  ansible.builtin.yum_repository:
    name: elasticsearch-7.x
    description: Elasticsearch repository for 7.x packages
    baseurl: "{{ elastic_baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ elastic_rpm_key }}"
    repo_gpgcheck: no

- name: Install Package
  ansible.builtin.dnf:
    name: "{{ elastic_package }}"
    state: present

- name: Deploy /etc/elasticsearch/elasticsearch.yml
  ansible.builtin.template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0660'
  notify: Restart Elasticsearch
  changed_when: true

- name: Add Service For Firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - "{{ graylog_listen }}/tcp"
    - "{{ rsyslog_listen }}/tcp"
    - "{{ rsyslog_listen }}/udp"
